export type Page = 'dashboard' | 'sources' | 'files' | 'pipeline' | 'review' | 'preview' | 'execution' | 'history' | 'settings'
export type Source = { id: string; name: string; path: string; status: 'ready'|'offline'|'scanning'; files: number; size: string; lastScan: string }
export type ApiSource = { id: string; name: string; root_path: string; enabled: boolean; read_only: boolean; exclusions: string[]; protected_paths: string[]; capabilities: Record<string, boolean|string> }
export type ProcessorConfig = { id: string; enabled: boolean; options: Record<string, unknown> }
export type ProcessorManifest = { id: string; version: string; category: string; requires: string[]; provides: string[]; default_enabled: boolean; score_weight: number; safety_class: string; option_schema: Record<string,unknown> }
export type Workflow = { id: string; name: string; preset: string; review_policy: string; current_revision: number }
export type WorkflowRevision = { id: string; workflow_id: string; revision: number; config: { processors?: ProcessorConfig[] }; created_at: string }
export type WorkflowCompare = { workflow_id: string; from_revision: number; to_revision: number; added: string[]; removed: string[]; changed: string[]; unchanged: string[] }
export type WorkflowPortable = { schema_version: 1; name: string; preset: string; review_policy: string; processors: ProcessorConfig[] }
export type Condition = { field: string; operator: 'equals'|'not_equals'|'contains'|'not_contains'|'starts_with'|'ends_with'|'regex'|'in'|'greater_than'|'less_than'|'is_true'|'is_false'; value?: unknown }
export type ConditionGroup = { mode: 'all'|'any'|'not'; conditions: Condition[]; groups: ConditionGroup[] }
export type WorkflowAction = { kind: 'run_processor'|'extract_dates'|'clean_name'|'remove_number_patterns'|'inherit_parent'|'render_name'|'keep'|'move'|'archive'|'quarantine'|'skip'|'require_review'; options: Record<string,unknown> }
export type RuleCard = { id: string; name: string; description: string; enabled: boolean; order: number; conditions: ConditionGroup; actions: WorkflowAction[]; on_match: 'continue'|'stop'|'skip'|'review' }
export type WorkflowStage = { id: 'scope'|'filter'|'extract'|'clean'|'classify'|'target'|'review'|'execute'; enabled: boolean; rules: RuleCard[] }
export type WorkflowTemplateV2 = { schema_version: 2; name: string; description: string; minimum_version: string; preset: 'rename_only'|'rename_and_organize'; review_policy: 'conservative'|'balanced'|'automatic'; conflict_policy: 'review'|'append_number'|'skip'|'stop'; required_processors: Record<string,string>; stages: WorkflowStage[]; examples: { input_path: string; expected_path?: string; expected_action?: string }[] }
export type TemplateValidation = { valid: boolean; template: WorkflowTemplateV2|null; errors: string[]; warnings: string[]; missing_processors: string[]; risks: string[] }
export type WorkflowImpact = { workflow_id: string; source_id: string; total: number; rename: number; move: number; archive: number; quarantine: number; unchanged: number; conflicts: number; review: number }
export type FileEntry = { id: string; source_id: string; relative_path: string; parent_path: string; name: string; extension: string; size: number; mtime_ns: number; is_dir: boolean }
export type FilePage = { items: FileEntry[]; total: number; limit: number; offset: number }
export type FileGroup = { id: string; source_id: string; group_key: string; group_type: string; member_ids: string[]; confidence: number; reasons: string[] }
export type PipelineRun = { id: string; source_id: string; workflow_id: string; workflow_revision: number; status: string; summary: Record<string, number> }
export type StageResult = { id: string; file_entry_id: string; processor_id: string; processor_version: string; status: string; confidence: number; input_data: Record<string, unknown>; output_data: Record<string, unknown>; reasons: string[]; warnings: string[] }
export type ReviewDecision = { id: string; run_id: string; file_entry_id: string; action: 'accept'|'keep'|'override'; target_relative_path: string|null; note: string|null; updated_at: string }
export type ReviewItem = { run_id: string; file_entry_id: string; relative_path: string; proposed_relative_path: string; confidence: number; reasons: string[]; warnings: string[]; processors: string[]; decision: ReviewDecision|null }
export type PlanOperation = { id: string; sequence: number; kind: string; source_relative_path: string; target_relative_path: string; expected_size: number; expected_mtime_ns: number; reasons: string[]; reversible: boolean }
export type PlanSummary = { id: string; run_id: string; source_id: string; status: string; frozen_at: string|null; confirmed_at: string|null; summary: Record<string, number>; operations: PlanOperation[] }
export type Batch = { id: string; plan_id: string; status: string; succeeded: number; failed: number; skipped: number; error: string|null; completed_at: string|null }
export type AuditLog = { id: string; batch_id: string|null; operation_id: string|null; event: string; status: string; details: Record<string, unknown>; created_at: string }
export type Schedule = { id: string; name: string; source_id: string; interval_minutes: number; enabled: boolean; next_run_at: string; last_run_at: string|null }
export type Backup = { filename: string; size: number; created_at: string }
export type Diagnostics = { version: string; worker_alive: boolean; database: string; config_writable: boolean; webhook_configured: boolean; counts: Record<string,number> }
export type Preflight = { status: 'ready'; operation_count: number }
export type RollbackPreview = { batch_id: string; ready: boolean; operations: { operation_id: string; source_relative_path: string; target_relative_path: string; ready: boolean; conflict: string|null }[] }
export type Health = { status: string; version?: string }
