import { ChevronLeft, ChevronRight, Lightbulb, Play, ShieldCheck, TriangleAlert } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { useI18n } from '../i18n'
import type { ApiSource, DraftWorkflowImpact, JunkRulePack, NameCleanupPack, NameCleanupPackVersion, RuleCard, WorkflowAction, WorkflowDiagnostic, WorkflowLiveSummary, WorkflowSimulation, WorkflowStage, WorkflowTemplateV2 } from '../types'

type Props={template:WorkflowTemplateV2;onChange:(template:WorkflowTemplateV2)=>void;sources:ApiSource[];sourceId:string;onSource:(id:string)=>void;packs:JunkRulePack[];live?:WorkflowLiveSummary|null;impact?:DraftWorkflowImpact|null;examplePath?:string;onExamplePath?:(value:string)=>void;onManualImpact?:()=>void;impactBusy?:boolean}
type Goal='rename'|'archive'|'media'|'images'|'downloads'|'junk'|'duplicates'|'custom'
type Question='goal'|'scope'|'recognize'|'rename'|'destination'|'protect'|'review'|'summary'
const questions:Question[]=['goal','scope','recognize','rename','destination','protect','review','summary']
const goals:{id:Goal;title:string;description:string}[]=[
  {id:'rename',title:'Clean file names only',description:'Remove unwanted text without moving files.'},
  {id:'archive',title:'Archive by year and month',description:'Recognize dates and organize files into year/month folders.'},
  {id:'media',title:'Organize media and sidecars',description:'Keep videos, subtitles, NFO and covers together.'},
  {id:'images',title:'Organize photos by date',description:'Recognize dates and archive common image files.'},
  {id:'downloads',title:'Clean a download folder',description:'Clean names and review advertisement or temporary files.'},
  {id:'junk',title:'Find junk files',description:'Use selected rule packs and send candidates to review.'},
  {id:'duplicates',title:'Find duplicate files',description:'Detect duplicate groups and review them.'},
  {id:'custom',title:'Build a custom workflow',description:'Choose every feature yourself.'},
]
const makeRule=(id:string,name:string,kind:WorkflowAction['kind'],options:Record<string,unknown>={}):RuleCard=>({id,name,description:'',enabled:true,order:0,conditions:{mode:'all',conditions:[],groups:[]},actions:[{kind,options}],on_match:'continue'})
const processorRule=(id:string,name:string,processor_id:string,options:Record<string,unknown>={})=>makeRule(id,name,'run_processor',{processor_id,...options})
const owner=(template:WorkflowTemplateV2,id:WorkflowStage['id'])=>template.stages.find(item=>item.id===id)
const actions=(template:WorkflowTemplateV2)=>template.stages.flatMap(stage=>stage.rules).flatMap(rule=>rule.actions)
const hasAction=(template:WorkflowTemplateV2,kind:WorkflowAction['kind'])=>actions(template).some(action=>action.kind===kind)
const hasProcessor=(template:WorkflowTemplateV2,id:string)=>actions(template).some(action=>action.kind==='run_processor'&&action.options.processor_id===id)
const actionOf=(template:WorkflowTemplateV2,kind:WorkflowAction['kind'])=>actions(template).find(action=>action.kind===kind)
const junkAction=(template:WorkflowTemplateV2)=>actions(template).find(action=>action.kind==='run_processor'&&action.options.processor_id==='detect_junk')
const setRule=(template:WorkflowTemplateV2,stageId:WorkflowStage['id'],rule:RuleCard,enabled=true)=>{const next=structuredClone(template);const stage=owner(next,stageId)!;stage.rules=stage.rules.filter(item=>item.id!==rule.id);if(enabled)stage.rules.push({...rule,order:stage.rules.length});stage.rules.forEach((item,index)=>item.order=index);return next}
const setTarget=(template:WorkflowTemplateV2,kind:'keep'|'move'|'archive',path_template='')=>{const next=structuredClone(template);const stage=owner(next,'target')!;stage.rules=stage.rules.filter(item=>!item.id.startsWith('guide.target.'));stage.rules.push({...makeRule(`guide.target.${kind}`,kind==='keep'?'Keep files in place':kind==='move'?'Move files':'Archive files',kind,path_template?{path_template,missing_date:'review'}:{}),order:stage.rules.length});return next}
const list=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)

function goalTemplate(template:WorkflowTemplateV2,goal:Goal){let next=structuredClone(template);next.stages=next.stages.map(stage=>({...stage,rules:stage.rules.filter(rule=>!rule.id.startsWith('guide.'))}));next.preset=goal==='rename'||goal==='junk'||goal==='duplicates'?'rename_only':'rename_and_organize';if(['rename','archive','media','images','downloads'].includes(goal))next=setRule(next,'clean',makeRule('guide.clean','Clean file names','clean_name',{remove_words:[],remove_prefixes:[],remove_suffixes:[],normalize_separators:true}));if(['archive','images'].includes(goal)){next=setRule(next,'extract',makeRule('guide.dates','Recognize dates','extract_dates'));next=setTarget(next,'archive','{year}/{month}')}else if(goal==='media'){next=setRule(next,'extract',processorRule('guide.quality','Recognize quality','extract_quality'));next=setTarget(next,'move','Media/{category}')}else next=setTarget(next,'keep');if(goal==='images')next.scope.include_extensions=['.jpg','.jpeg','.png','.webp','.heic'];if(goal==='media')next.scope.include_extensions=['.mkv','.mp4','.avi','.srt','.ass','.nfo','.jpg','.png'];if(goal==='downloads'||goal==='junk')next=setRule(next,'classify',processorRule('guide.junk','Detect junk files','detect_junk',{rule_pack_selection:'required'}));if(goal==='duplicates')next=setRule(next,'classify',processorRule('guide.duplicates','Detect duplicate files','detect_duplicates',{method:'hash'}));return next}

export function BusinessWorkflowBuilder({template,onChange,sources,sourceId,onSource,packs}:Props){
  const {t}=useI18n();const [question,setQuestion]=useState<Question>('goal');const [goal,setGoal]=useState<Goal>('custom');const [samples,setSamples]=useState('parent/example_2026.1.5.mp4\ndownloads/advertisement.url');const [sampleResults,setSampleResults]=useState<WorkflowSimulation[]>([]);const [sampleBusy,setSampleBusy]=useState(false);const [details,setDetails]=useState(false)
  const [cleanupPacks,setCleanupPacks]=useState<NameCleanupPack[]>([]);const [cleanupVersions,setCleanupVersions]=useState<Record<string,NameCleanupPackVersion[]>>({});const [cleanupSearch,setCleanupSearch]=useState('')
  useEffect(()=>{void api.nameCleanupPacks().then(rows=>{setCleanupPacks(rows);for(const pack of rows)void api.nameCleanupPackVersions(pack.id).then(versions=>setCleanupVersions(current=>({...current,[pack.id]:versions})))})},[])
  const selectedSource=sources.find(item=>item.id===sourceId);const detector=junkAction(template);const refs=(detector?.options.rule_pack_refs as {pack_id?:string;id?:string;version:number|string}[]|undefined)??[]
  const archive=actionOf(template,'archive');const move=actionOf(template,'move');const diagnostics=useMemo<WorkflowDiagnostic[]>(()=>{const result:WorkflowDiagnostic[]=[];if(!sourceId)result.push({severity:'error',code:'source',stage_id:'scope',rule_id:null,message:'Select a source before preview.',suggestion:'Choose a local indexed source.'});if(detector&&!refs.length)result.push({severity:'error',code:'junk-pack',stage_id:'classify',rule_id:null,message:'Junk detection needs a selected rule pack.',suggestion:'Choose one recommended pack.'});if(archive&&String(archive.options.path_template??'').includes('{year}')&&!hasAction(template,'extract_dates'))result.push({severity:'error',code:'dates',stage_id:'extract',rule_id:null,message:'Date archive needs date recognition.',suggestion:'Add the safe date recognition dependency.'});if((archive||move)&&!String((archive??move)?.options.path_template??''))result.push({severity:'error',code:'target',stage_id:'target',rule_id:null,message:'The destination folder is empty.',suggestion:'Enter a relative folder template.'});return result},[template,sourceId,detector,refs.length,archive,move])
  const completed=6-diagnostics.length;const index=questions.indexOf(question);const recommendations=packs.filter(pack=>goal==='downloads'||goal==='junk'?pack.id.includes('bt')||pack.name.toLowerCase().includes('advert'):false)
  const chooseGoal=(value:Goal)=>{setGoal(value);onChange(goalTemplate(template,value));setQuestion('scope')}
  const choosePack=async(pack:JunkRulePack)=>{const next=structuredClone(template);const action=junkAction(next);if(!action)return;const snapshot=await api.junkRulePack(pack.id,pack.current_version);action.options={processor_id:'detect_junk',rule_pack_refs:[{pack_id:pack.id,version:pack.current_version}],rule_packs:[{...snapshot,source:'snapshot',read_only:true}]};onChange(next)}
  const chooseCleanupPack=async(pack:NameCleanupPack,enabled:boolean,version=pack.current_version)=>{const next=structuredClone(template);const action=actionOf(next,'clean_name');if(!action)return;const snapshots=((action.options.cleanup_packs as NameCleanupPack[]|undefined)??[]).filter(item=>item.id!==pack.id);const refs=((action.options.cleanup_pack_refs as {pack_id:string;version:number}[]|undefined)??[]).filter(item=>item.pack_id!==pack.id);if(enabled){const snapshot=await api.nameCleanupPack(pack.id,version);snapshots.push({...snapshot,source:'snapshot',read_only:true});refs.push({pack_id:pack.id,version})}action.options.cleanup_packs=snapshots;action.options.cleanup_pack_refs=refs;onChange(next)}
  const moveCleanupPack=(packId:string,delta:number)=>{const next=structuredClone(template);const action=actionOf(next,'clean_name');if(!action)return;const snapshots=[...((action.options.cleanup_packs as NameCleanupPack[]|undefined)??[])];const refs=[...((action.options.cleanup_pack_refs as {pack_id:string;version:number}[]|undefined)??[])];const index=snapshots.findIndex(item=>item.id===packId);const target=index+delta;if(index<0||target<0||target>=snapshots.length)return;[snapshots[index],snapshots[target]]=[snapshots[target],snapshots[index]];[refs[index],refs[target]]=[refs[target],refs[index]];action.options.cleanup_packs=snapshots;action.options.cleanup_pack_refs=refs;onChange(next)}
  const simulateSamples=async()=>{setSampleBusy(true);try{setSampleResults(await Promise.all(list(samples.replaceAll('\n',',')).slice(0,20).map(path=>api.simulateWorkflow(template,path))))}finally{setSampleBusy(false)}}
  const repair=(code:string)=>{if(code==='dates')onChange(setRule(template,'extract',makeRule('guide.dates','Recognize dates','extract_dates')));if(code==='target')onChange(setTarget(template,archive?'archive':'move',archive?'{year}/{month}':'Organized'))}
  const updateProtection=(key:keyof WorkflowTemplateV2['protection'],value:string)=>onChange({...template,protection:{...template.protection,[key]:list(value)}})
  return <div className="guided-builder">
    <section className="panel guided-progress"><div><div className="section-kicker">{t('GUIDED WORKFLOW')}</div><h2>{t('Answer one question at a time')}</h2><p>{t('No full-library calculation runs while you edit. Generate a preview only after the rules are confirmed.')}</p></div><div className="completion-meter"><strong>{completed}/6</strong><span>{t(diagnostics.length?'Configuration incomplete':'Ready to preview')}</span><div><i style={{width:`${Math.max(0,completed/6*100)}%`}}/></div></div></section>
    <div className="guided-layout"><aside className="panel guided-questions">{questions.map((item,position)=><button key={item} className={item===question?'active':position<index?'done':''} onClick={()=>setQuestion(item)}><span>{position+1}</span><strong>{t(item==='goal'?'Choose a goal':item==='scope'?'Choose files':item==='recognize'?'Choose recognition':item==='rename'?'Choose name changes':item==='destination'?'Choose destination':item==='protect'?'Protect files':item==='review'?'Choose review':'Confirm rules')}</strong></button>)}</aside>
      <main className="panel guided-question"><div className="question-heading"><div className="section-kicker">{t(`QUESTION ${index+1} OF ${questions.length}`)}</div><h2>{t(question==='goal'?'What result do you want?':question==='scope'?'Which files should be included?':question==='recognize'?'What should File Curator recognize?':question==='rename'?'How should names change?':question==='destination'?'Where should files go?':question==='protect'?'What must never be processed?':question==='review'?'How should uncertain results be handled?':'Confirm the workflow rules')}</h2></div>
      {question==='goal'&&<div className="goal-grid">{goals.map(item=><button className={goal===item.id?'selected':''} key={item.id} onClick={()=>chooseGoal(item.id)}><strong>{t(item.title)}</strong><small>{t(item.description)}</small></button>)}</div>}
      {question==='scope'&&<div className="guided-form"><label>{t('Source')}<select className="text-input" value={sourceId} onChange={event=>onSource(event.target.value)}><option value="">{t('Select source')}</option>{sources.map(source=><option key={source.id} value={source.id}>{source.name}</option>)}</select></label><label className="checkbox-line"><input type="checkbox" checked={template.scope.include_subdirectories} onChange={event=>onChange({...template,scope:{...template.scope,include_subdirectories:event.target.checked}})}/><span>{t('Include subdirectories')}</span></label><label>{t('Include extensions')}<input className="text-input" value={template.scope.include_extensions.join(', ')} onChange={event=>onChange({...template,scope:{...template.scope,include_extensions:list(event.target.value)}})} placeholder=".mp4, .mkv"/></label><label>{t('Exclude paths')}<input className="text-input" value={template.scope.exclude_paths.join(', ')} onChange={event=>onChange({...template,scope:{...template.scope,exclude_paths:list(event.target.value)}})}/></label></div>}
      {question==='recognize'&&<div className="guided-form"><label className="checkbox-line"><input type="checkbox" checked={hasAction(template,'extract_dates')} onChange={event=>onChange(setRule(template,'extract',makeRule('guide.dates','Recognize dates','extract_dates'),event.target.checked))}/><span>{t('Recognize dates')}</span></label><label className="checkbox-line"><input type="checkbox" checked={hasProcessor(template,'extract_identifier')} onChange={event=>onChange(setRule(template,'extract',processorRule('guide.identifiers','Recognize identifiers','extract_identifier'),event.target.checked))}/><span>{t('Recognize identifiers')}</span></label><label className="checkbox-line"><input type="checkbox" checked={hasProcessor(template,'detect_duplicates')} onChange={event=>onChange(setRule(template,'classify',processorRule('guide.duplicates','Detect duplicate files','detect_duplicates',{method:'hash'}),event.target.checked))}/><span>{t('Detect duplicate files')}</span></label>{detector&&<section className="recommendation"><Lightbulb size={17}/><div><strong>{t('Recommended rule packs')}</strong><small>{t('Recommendations are never selected automatically.')}</small>{recommendations.length?recommendations.map(pack=><button key={pack.id} className="button secondary" onClick={()=>void choosePack(pack)}>{t('Use')} {t(pack.name)} v{pack.current_version}</button>):<span>{t('Choose a pack from the junk rules page or imported template.')}</span>}</div></section>}</div>}
      {question==='rename'&&<div className="guided-form"><label className="checkbox-line"><input type="checkbox" checked={hasAction(template,'clean_name')} onChange={event=>onChange(setRule(template,'clean',makeRule('guide.clean','Clean file names','clean_name',{remove_words:[],cleanup_pack_refs:[],cleanup_packs:[],normalize_separators:true}),event.target.checked))}/><span>{t('Clean file names')}</span></label>{hasAction(template,'clean_name')&&<><section className="cleanup-picker"><div><strong>{t('Name cleanup rule packs')}</strong><small>{t('Select reusable packs. They run in the order shown.')}</small></div><input className="text-input" value={cleanupSearch} onChange={event=>setCleanupSearch(event.target.value)} placeholder={t('Search cleanup packs')}/>{cleanupPacks.filter(pack=>pack.name.toLowerCase().includes(cleanupSearch.toLowerCase())).map(pack=>{const refs=(actionOf(template,'clean_name')?.options.cleanup_pack_refs as {pack_id:string;version:number}[]|undefined)??[];const selected=refs.some(item=>item.pack_id===pack.id);const version=refs.find(item=>item.pack_id===pack.id)?.version??pack.current_version;return <div className="cleanup-choice" key={pack.id}><label><input type="checkbox" checked={selected} onChange={event=>void chooseCleanupPack(pack,event.target.checked,version)}/><span><strong>{t(pack.name)}</strong><small>{pack.rules.length} {t('rules')} · {pack.protected_names.length+pack.protected_keywords.length+pack.protected_regex.length} {t('protected items')}</small></span></label><select disabled={!selected} value={version} onChange={event=>void chooseCleanupPack(pack,true,Number(event.target.value))}>{(cleanupVersions[pack.id]??[]).map(item=><option value={item.version} key={item.version}>v{item.version}</option>)}</select>{selected&&<span className="cleanup-order"><button onClick={()=>moveCleanupPack(pack.id,-1)}>↑</button><button onClick={()=>moveCleanupPack(pack.id,1)}>↓</button></span>}</div>})}</section><label>{t('Workflow-specific keywords')}<input className="text-input" value={String(actionOf(template,'clean_name')?.options.remove_words??'')} onChange={event=>{const next=structuredClone(template);const action=actionOf(next,'clean_name');if(action)action.options.remove_words=list(event.target.value);onChange(next)}}/></label></>}<label className="checkbox-line"><input type="checkbox" checked={hasAction(template,'inherit_parent')} onChange={event=>onChange(setRule(template,'clean',makeRule('guide.parent','Inherit parent folder name','inherit_parent',{separator:''}),event.target.checked))}/><span>{t('Inherit parent folder name')}</span></label></div>}
      {question==='destination'&&<div className="goal-grid">{(['keep','move','archive'] as const).map(kind=><button key={kind} className={hasAction(template,kind)?'selected':''} onClick={()=>onChange(setTarget(template,kind,kind==='move'?'Organized':kind==='archive'?'{year}/{month}':''))}><strong>{t(kind==='keep'?'Rename only':kind==='move'?'Move to folder':'Archive by template')}</strong></button>)}</div>}
      {question==='protect'&&<div className="guided-form"><div className="protection-level"><ShieldCheck size={17}/><span><strong>{t('Global protection')}</strong><small>{t('System and hidden paths are always protected by safety rules.')}</small></span></div><div className="protection-level"><ShieldCheck size={17}/><span><strong>{t('Source protection')}</strong><small>{selectedSource?.protected_paths.join(', ')||t('No source-specific protected paths.')}</small></span></div><label>{t('Workflow protected paths')}<input className="text-input" value={template.protection.protected_paths.join(', ')} onChange={event=>updateProtection('protected_paths',event.target.value)}/></label><label>{t('Protected extensions')}<input className="text-input" value={template.protection.protected_extensions.join(', ')} onChange={event=>updateProtection('protected_extensions',event.target.value)} placeholder=".nfo, .srt"/></label><label>{t('Protected file names')}<input className="text-input" value={template.protection.protected_names.join(', ')} onChange={event=>updateProtection('protected_names',event.target.value)}/></label><label>{t('Protected name keywords')}<input className="text-input" value={template.protection.protected_keywords.join(', ')} onChange={event=>updateProtection('protected_keywords',event.target.value)}/></label><details><summary>{t('Expert protection regular expressions')}</summary><input className="text-input" value={template.protection.protected_regex.join(', ')} onChange={event=>updateProtection('protected_regex',event.target.value)}/></details></div>}
      {question==='review'&&<div className="guided-form"><label>{t('Conflict policy')}<select className="text-input" value={template.conflict_policy} onChange={event=>onChange({...template,conflict_policy:event.target.value as WorkflowTemplateV2['conflict_policy']})}><option value="review">{t('Review')}</option><option value="append_number">{t('Append number')}</option><option value="skip">{t('Skip')}</option><option value="stop">{t('Stop plan')}</option></select></label><label>{t('Maximum operations')}<input className="text-input" type="number" min="1" value={template.impact_threshold.max_operations??''} onChange={event=>onChange({...template,impact_threshold:{...template.impact_threshold,max_operations:event.target.value?Number(event.target.value):null}})}/></label></div>}
      {question==='summary'&&<div className="rule-confirmation"><div className="natural-summary"><strong>{t('Workflow summary')}</strong><p>{t('Process')} {selectedSource?.name??t('no source')}; {t('recognize')} {hasAction(template,'extract_dates')?t('dates'):t('basic metadata')}; {t('destination')} {hasAction(template,'archive')?t('archive'):hasAction(template,'move')?t('move'):t('keep current folders')}.</p></div>{diagnostics.map(item=><div className="repair-item" key={item.code}><TriangleAlert size={15}/><span><strong>{t(item.message)}</strong><small>{t(item.suggestion)}</small></span>{['dates','target'].includes(item.code)&&<button className="button secondary" onClick={()=>repair(item.code)}>{t('Apply safe fix')}</button>}</div>)}<section className="sample-sandbox"><div><strong>{t('Multi-file example sandbox')}</strong><small>{t('This tests only the names below and does not calculate the full library.')}</small></div><textarea value={samples} onChange={event=>setSamples(event.target.value)} placeholder={t('One relative path per line')}/><button className="button secondary" disabled={sampleBusy} onClick={()=>void simulateSamples()}><Play size={14}/>{t(sampleBusy?'Testing...':'Test examples')}</button>{sampleResults.map(result=><div className="sample-result" key={result.original_path}><code>{result.original_path}</code><ChevronRight size={14}/><code>{result.proposed_path}</code><span>{t(result.action)}</span></div>)}</section><button className="button quiet" onClick={()=>setDetails(value=>!value)}>{t(details?'Hide technical summary':'Show technical summary')}</button>{details&&<pre className="rule-test-result">{JSON.stringify(template.stages.flatMap(stage=>stage.rules.map(rule=>({stage:stage.id,rule:rule.name,actions:rule.actions.map(action=>action.kind)}))),null,2)}</pre>}</div>}
      <footer className="question-actions"><button className="button secondary" disabled={index===0} onClick={()=>setQuestion(questions[index-1])}><ChevronLeft size={14}/>{t('Previous')}</button><span>{index+1}/{questions.length}</span><button className="button primary" disabled={index===questions.length-1} onClick={()=>setQuestion(questions[index+1])}>{t('Next')}<ChevronRight size={14}/></button></footer></main>
    </div>
  </div>
}
