import { Check, Plus } from 'lucide-react'
import { useI18n } from '../i18n'
import type { Page, PlanSummary, Workflow } from '../types'

export function DashboardPage({ setPage, state, workflows, plans }: { setPage: (page: Page) => void; state: 'loading'|'live'|'offline'; workflows: Workflow[]; plans: PlanSummary[] }) {
  const {t}=useI18n()
  return <><div className="page-header"><div><div className="eyebrow">FILE CURATOR</div><h1>{t('Workspace overview')}</h1><p>{t('Review indexed metadata and virtual plans before touching any files.')}</p></div><div className="header-actions"><span className={`badge ${state === 'live' ? 'green' : state === 'loading' ? 'blue' : 'red'}`}>{t(state === 'live' ? 'Live API' : state === 'loading' ? 'Connecting' : 'API unavailable')}</span><button className="button secondary" onClick={() => setPage('sources')}><Plus size={14}/> {t('Add source')}</button><button className="button primary" onClick={() => setPage('preview')}>{t('Preview plan')}</button></div></div><div className="stats-grid"><Stat label={t('Data mode')} value={t('Metadata')} meta={t('Real files remain unchanged')} tone="blue"/><Stat label={t('Safety boundary')} value={t('Frozen plan')} meta={t('Confirmation required')} tone="amber"/><Stat label={t('Workflows')} value={String(workflows.length)} meta={t('Deterministic pipelines')} tone="green"/><Stat label={t('Plans')} value={String(plans.length)} meta={t('Draft, frozen and executed')} tone="purple"/></div><section className="panel pipeline-card"><div className="panel-heading"><div><div className="section-kicker">{t('ACTIVE WORKFLOW')}</div><h2>{workflows[0]?.name || t('Create your first workflow')}</h2></div>{workflows[0]&&<span className="badge blue">{t(`Revision ${workflows[0].current_revision}`)}</span>}</div><div className="flow-line">{['Scan','Extract','Normalize','Group','Target','Review'].map((step,i)=><div className="flow-step" key={step}><span className={i < 4 ? 'done' : i === 4 ? 'current' : ''}>{i < 4 ? <Check size={11}/> : i + 1}</span><label>{t(step)}</label></div>)}</div><div className="card-footer"><span>{t('Simulation only until a plan is frozen and confirmed')}</span><button className="button quiet" onClick={() => setPage('pipeline')}>{t('Configure workflow')}</button></div></section></>
}

function Stat({label,value,meta,tone}:{label:string;value:string;meta:string;tone:string}) { return <div className={`stat ${tone}`}><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-meta">{meta}</div></div> }
