import { ArrowDown, ArrowUp, Copy, Plus, Save, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api } from '../api'
import { useI18n } from '../i18n'
import type { NameCleanupPack, NameCleanupPackVersion, NameCleanupPackWrite, NameCleanupRule, Workflow } from '../types'

type Props={workflows:Workflow[];notify:(message:string)=>void;refresh:()=>Promise<void>}
const values=(text:string)=>text.split(',').map(item=>item.trim()).filter(Boolean)
const newRule=(order:number):NameCleanupRule=>({id:`cleanup.${Date.now()}.${order}`,name:'New cleanup rule',description:'',enabled:true,order,kind:'remove_contains',pattern:'',replacement:'',extensions:[],path_contains:[],stop_on_match:false,examples:[]})
const newPack=():NameCleanupPack=>({id:'',version:'0',name:'New name cleanup pack',description:'',protected_names:[],protected_keywords:[],protected_regex:[],normalize_separators:true,normalize_width:false,deduplicate_words:true,max_name_length:240,rules:[newRule(0)],source:'personal',read_only:false,current_version:0})
const writable=(pack:NameCleanupPack,note:string):NameCleanupPackWrite=>({name:pack.name,description:pack.description,protected_names:pack.protected_names,protected_keywords:pack.protected_keywords,protected_regex:pack.protected_regex,normalize_separators:pack.normalize_separators,normalize_width:pack.normalize_width,deduplicate_words:pack.deduplicate_words,max_name_length:pack.max_name_length,rules:pack.rules,change_note:note})

export function NameCleanupPage({workflows,notify,refresh}:Props){
  const {t}=useI18n();const [packs,setPacks]=useState<NameCleanupPack[]>([]);const [pack,setPack]=useState<NameCleanupPack|null>(null);const [ruleId,setRuleId]=useState('');const [versions,setVersions]=useState<NameCleanupPackVersion[]>([]);const [viewVersion,setViewVersion]=useState(0);const [note,setNote]=useState('');const [workflowId,setWorkflowId]=useState('');const [example,setExample]=useState('[www.example.com] 广告_movie_2026-01-05.mp4');const [result,setResult]=useState('');const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);const [errors,setErrors]=useState<string[]>([])
  const load=async(select?:string)=>{const rows=await api.nameCleanupPacks();setPacks(rows);const next=rows.find(item=>item.id===(select??pack?.id))??rows[0]??null;setPack(next?structuredClone(next):null);setRuleId(next?.rules[0]?.id??'');if(next){setViewVersion(next.current_version);setVersions(await api.nameCleanupPackVersions(next.id))}}
  useEffect(()=>{void load().finally(()=>setLoaded(true))},[])
  const locked=Boolean(pack?.read_only)||Boolean(pack&&viewVersion!==pack.current_version)
  const rule=pack?.rules.find(item=>item.id===ruleId)
  const select=async(value:NameCleanupPack)=>{setPack(structuredClone(value));setRuleId(value.rules[0]?.id??'');setViewVersion(value.current_version);setVersions(await api.nameCleanupPackVersions(value.id));setErrors([])}
  const change=(update:Partial<NameCleanupPack>)=>setPack(current=>current?{...current,...update}:current)
  const changeRule=(update:Partial<NameCleanupRule>)=>setPack(current=>current?{...current,rules:current.rules.map(item=>item.id===ruleId?{...item,...update}:item)}:current)
  const save=async()=>{if(!pack)return;setBusy(true);try{const validation=await api.validateNameCleanupPack({...pack,id:pack.id||'draft-cleanup',version:pack.version||'1'});if(!validation.valid){setErrors(validation.errors);return}const saved=pack.id?await api.updateNameCleanupPack(pack.id,writable(pack,note)):await api.createNameCleanupPack(writable(pack,note));setNote('');await load(saved.id);notify('Name cleanup pack saved')}catch(cause){notify(cause instanceof Error?cause.message:'cleanup.pack_save_failed')}finally{setBusy(false)}}
  const copy=async()=>{if(pack?.id){const saved=await api.copyNameCleanupPack(pack.id);await load(saved.id);notify('Name cleanup pack copied')}}
  const remove=async()=>{if(pack?.id&&!pack.read_only){await api.deleteNameCleanupPack(pack.id);setPack(null);await load();notify('Name cleanup pack deleted')}}
  const apply=async()=>{if(pack?.id&&workflowId){await api.applyNameCleanupPack(pack.id,workflowId,viewVersion);await refresh();notify('Name cleanup pack applied')}}
  const simulate=async()=>{if(pack){const value=await api.simulateNameCleanupPack(pack,example);setResult(`${value.original_path} -> ${value.proposed_name}\n${value.reasons.join('\n')}`)}}
  const move=(delta:number)=>{if(!pack||!rule)return;const index=pack.rules.findIndex(item=>item.id===rule.id);const target=index+delta;if(target<0||target>=pack.rules.length)return;const rows=[...pack.rules];[rows[index],rows[target]]=[rows[target],rows[index]];change({rules:rows.map((item,order)=>({...item,order}))})}
  return <><div className="page-header"><div><div className="eyebrow">{t('NAME CLEANUP LIBRARY')}</div><h1>{t('Name cleanup')}</h1><p>{t('Build reusable, versioned rules for cleaning file names.')}</p></div><div className="header-actions"><button className="button secondary" disabled={!loaded} onClick={()=>{const value=newPack();setPack(value);setRuleId(value.rules[0].id);setVersions([]);setViewVersion(0)}}><Plus size={14}/>{t('New cleanup pack')}</button><button className="button secondary" disabled={!pack?.id||busy} onClick={()=>void copy()}><Copy size={14}/>{t('Copy')}</button><button className="button primary" disabled={!pack||locked||busy} onClick={()=>void save()}><Save size={14}/>{t('Save new version')}</button></div></div>
  <section className="panel cleanup-apply"><div><strong>{t('Apply a fixed version to a workflow')}</strong><small>{t('The workflow stores both the reference and a complete snapshot.')}</small></div><select className="text-input" value={workflowId} onChange={event=>setWorkflowId(event.target.value)}><option value="">{t('Select workflow')}</option>{workflows.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="button secondary" disabled={!pack?.id||!workflowId} onClick={()=>void apply()}>{t('Apply selected version')}</button></section>
  <div className="cleanup-manager"><aside className="panel cleanup-pack-list"><div className="section-kicker">{t('RULE PACKS')}</div>{packs.map(item=><button className={item.id===pack?.id?'junk-pack selected':'junk-pack'} key={item.id} onClick={()=>void select(item)}><span><strong>{t(item.name)}</strong><small>v{item.current_version} · {item.rules.length} {t('rules')}</small></span></button>)}</aside>{pack&&<main className="panel cleanup-editor"><div className="cleanup-meta"><label>{t('Pack name')}<input className="text-input" disabled={locked} value={pack.name} onChange={event=>change({name:event.target.value})}/></label><label>{t('Description')}<input className="text-input" disabled={locked} value={pack.description} onChange={event=>change({description:event.target.value})}/></label><label>{t('Version')}<select className="text-input" value={viewVersion} onChange={async event=>{const version=Number(event.target.value);setViewVersion(version);setPack(await api.nameCleanupPack(pack.id,version))}}>{versions.map(item=><option value={item.version} key={item.version}>v{item.version}</option>)}</select></label></div>
  <div className="cleanup-options"><label>{t('Protected names')}<input className="text-input" disabled={locked} value={pack.protected_names.join(', ')} onChange={event=>change({protected_names:values(event.target.value)})}/></label><label>{t('Protected keywords')}<input className="text-input" disabled={locked} value={pack.protected_keywords.join(', ')} onChange={event=>change({protected_keywords:values(event.target.value)})}/></label><label>{t('Protected regex')}<input className="text-input" disabled={locked} value={pack.protected_regex.join(', ')} onChange={event=>change({protected_regex:values(event.target.value)})}/></label><label>{t('Maximum name length')}<input className="text-input" type="number" min="1" max="255" disabled={locked} value={pack.max_name_length} onChange={event=>change({max_name_length:Number(event.target.value)})}/></label><label className="checkbox-line"><input type="checkbox" disabled={locked} checked={pack.normalize_separators} onChange={event=>change({normalize_separators:event.target.checked})}/><span>{t('Normalize separators')}</span></label><label className="checkbox-line"><input type="checkbox" disabled={locked} checked={pack.normalize_width} onChange={event=>change({normalize_width:event.target.checked})}/><span>{t('Normalize character width')}</span></label><label className="checkbox-line"><input type="checkbox" disabled={locked} checked={pack.deduplicate_words} onChange={event=>change({deduplicate_words:event.target.checked})}/><span>{t('Remove duplicate words')}</span></label></div>
  <div className="cleanup-workspace"><aside className="cleanup-rule-list"><div className="subsection-heading"><strong>{t('Rules')}</strong><button className="button secondary" disabled={locked} onClick={()=>{const next=newRule(pack.rules.length);change({rules:[...pack.rules,next]});setRuleId(next.id)}}><Plus size={13}/>{t('Add rule')}</button></div>{pack.rules.map(item=><button className={item.id===ruleId?'junk-rule-item selected':'junk-rule-item'} key={item.id} onClick={()=>setRuleId(item.id)}><span>{item.order+1}</span><div><strong>{item.name}</strong><small>{t(item.kind.replaceAll('_',' '))}: {item.pattern}</small></div><em className={item.enabled?'on':''}/></button>)}</aside>{rule&&<section className="cleanup-rule-editor"><div className="rule-toolbar"><button disabled={locked} onClick={()=>move(-1)}><ArrowUp size={14}/></button><button disabled={locked} onClick={()=>move(1)}><ArrowDown size={14}/></button><button disabled={locked} onClick={()=>{change({rules:pack.rules.filter(item=>item.id!==rule.id)});setRuleId('')}}><Trash2 size={14}/></button></div><label>{t('Rule name')}<input className="text-input" disabled={locked} value={rule.name} onChange={event=>changeRule({name:event.target.value})}/></label><label className="checkbox-line"><input type="checkbox" disabled={locked} checked={rule.enabled} onChange={event=>changeRule({enabled:event.target.checked})}/><span>{t('Enabled')}</span></label><label>{t('Rule type')}<select className="text-input" disabled={locked} value={rule.kind} onChange={event=>changeRule({kind:event.target.value as NameCleanupRule['kind']})}>{['remove_contains','remove_prefix','remove_suffix','literal_replace','regex_replace'].map(kind=><option key={kind} value={kind}>{t(kind.replaceAll('_',' '))}</option>)}</select></label><label>{t('Pattern or text')}<input className="text-input" disabled={locked} value={rule.pattern} onChange={event=>changeRule({pattern:event.target.value})}/></label>{['literal_replace','regex_replace'].includes(rule.kind)&&<label>{t('Replacement')}<input className="text-input" disabled={locked} value={rule.replacement} onChange={event=>changeRule({replacement:event.target.value})}/></label>}<label>{t('File extensions')}<input className="text-input" disabled={locked} value={rule.extensions.join(', ')} onChange={event=>changeRule({extensions:values(event.target.value)})}/></label><label>{t('Path contains')}<input className="text-input" disabled={locked} value={rule.path_contains.join(', ')} onChange={event=>changeRule({path_contains:values(event.target.value)})}/></label></section>}</div>
  <section className="cleanup-simulator"><label>{t('Example relative path')}<input className="text-input" value={example} onChange={event=>setExample(event.target.value)}/></label><button className="button secondary" onClick={()=>void simulate()}>{t('Test cleanup')}</button>{result&&<pre>{result}</pre>}</section>{!locked&&<label>{t('Version note')}<input className="text-input" value={note} onChange={event=>setNote(event.target.value)}/></label>}{errors.length>0&&<div className="junk-validation-errors">{errors.map(item=><span key={item}>{item}</span>)}</div>}<details className="developer-options"><summary>{t('Developer options (JSON)')}</summary><pre className="rule-test-result">{JSON.stringify(pack,null,2)}</pre></details>{pack.id&&!pack.read_only&&<button className="button danger" onClick={()=>void remove()}>{t('Delete rule pack')}</button>}</main>}</div></>
}
