import { Folder, Play, Plus, X } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api'
import type { Source } from '../types'

export function SourcesPage({ data, state, error, refresh, notify }: { data: Source[]; state: 'loading'|'live'|'offline'; error: string|null; refresh: () => Promise<void>; notify: (message:string) => void }) {
  const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [path,setPath]=useState(''); const [readOnly,setReadOnly]=useState(false); const [busy,setBusy]=useState(false); const [formError,setFormError]=useState('')
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setFormError(''); try { await api.createSource({name,root_path:path,read_only:readOnly}); await refresh(); setOpen(false); setName(''); setPath(''); notify('Source added') } catch(cause) { setFormError(cause instanceof Error ? cause.message : 'Could not add source') } finally { setBusy(false) } }
  const scan = async (source: Source, hashContents=false) => { try { await api.createScan(source.id,hashContents); notify(`${hashContents?'Content hash':'Metadata'} scan queued for ${source.name}`); await refresh() } catch(cause) { notify(cause instanceof Error ? cause.message : 'Could not queue scan') } }
  return <><div className="page-header"><div><div className="eyebrow">LOCAL FILESYSTEM</div><h1>Sources</h1><p>Directories indexed by File Curator. Standard scans read metadata only.</p></div><div className="header-actions"><span className={`badge ${state==='live'?'green':state==='loading'?'blue':'red'}`}>{state==='live'?'Connected':state==='loading'?'Loading':'Unavailable'}</span><button className="button primary" onClick={()=>setOpen(true)} disabled={state!=='live'}><Plus size={14}/> Add source</button></div></div>{state==='offline'&&<div className="api-notice">The API is unavailable ({error}). Start the API to manage sources.</div>}<div className="source-grid">{data.map(source=><section className="panel source-card" key={source.id}><div className="source-top"><div className="folder-icon"><Folder size={18}/></div><span className={`badge ${source.status==='ready'?'green':source.status==='scanning'?'blue':'red'}`}>{source.status}</span></div><h2>{source.name}</h2><code>{source.path}</code><div className="source-metrics"><span><strong>{source.files.toLocaleString()}</strong> indexed count pending</span><span><strong>{source.size}</strong></span></div><div className="source-foot"><span className="muted">{source.lastScan}</span><div><button className="button quiet" onClick={()=>void scan(source)}><Play size={13}/> Scan metadata</button><button className="button quiet" onClick={()=>void scan(source,true)}>Hash contents</button></div></div></section>)}</div>{open&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={create} onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><div className="section-kicker">NEW SOURCE</div><h2>Add local directory</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X size={16}/></button></div><label className="form-label">Display name</label><input className="text-input" value={name} onChange={event=>setName(event.target.value)} required placeholder="Media library"/><label className="form-label">Absolute path</label><input className="text-input" value={path} onChange={event=>setPath(event.target.value)} required placeholder="/volume1/media"/><label className="checkbox-line"><input type="checkbox" checked={readOnly} onChange={event=>setReadOnly(event.target.checked)}/><span>Read-only source</span></label>{formError&&<div className="form-error">{formError}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Adding source...':'Add source'}</button></div></form></div>}</>
}
